[window]
padding = { x = 4, y = 2 }
opacity = 0.70
blur = true
startup_mode = "Fullscreen"

[scrolling]
history = 100000
multiplier = 5

[font]
size = 12.0
offset = { x = 0, y = 4 }
normal = { family = "PlemolJP Console NF", style="Regular" }
bold = { family = "PlemolJP Console NF", style="Bold" }
italic = { family = "PlemolJP Console NF", style="Italic" }
bold_italic = { family = "PlemolJP Console NF", style="Bold Italic" }

[general]
import = [
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

